language: java
os: linux
env:
  - PRODUCTION=true
before_install:
  - echo "before_install"
jobs:
  include:
  - stage: Test, compile and build
    script:
    - mvn test -B
    - mvn build